---
title: "Correlation Heart Disease"
author: "Cynthia Sandor"
date: 'Last update: `r date()`'
output:
  html_document:
    fig_height: 5
    fig_width: 5
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 5
  pdf_document:
    toc: yes
---



```{r setup, include=FALSE}
setwd('/Users/dpag0499/Documents/PROJECTS/PPMI/src/test_cor_heart_disease')
library(phenix)
library(ggplot2)
library(plyr)
source("multiple_plot.R")
```

## Get the phenotype observation and phenotypic axis


```{r get phenotype observation and phenotypic axis ,echo=FALSE}
Clinical_Heart<-read.table('/Users/dpag0499/Documents/PROJECTS/PPMI/data/Discovery_dataset_Vascular_Disease.txt',header=T,sep='\t')
load("/Users/dpag0499/Documents/PROJECTS/PPMI/src/run_phenix/ODPC.Rdata")
```

```{r merge ,echo=FALSE}
S<-data.frame(-1*out$S[,c(1:3)])
S$SubjID<-row.names(Y_temp)
S_m<-melt(S,id.vars = c("SubjID"))
row.names(Clinical_Heart)<-Clinical_Heart$SubjID
Clinical_Heart_m <- melt(Clinical_Heart[,c(1,5:9)], id.vars=c("SubjID"))
colnames(Clinical_Heart_m)[2]<-"Trait"
Clinical_Heart_S<-merge(Clinical_Heart_m,S_m,by=c("SubjID"))
colnames(Clinical_Heart_S)[3]<-"Value"
colnames(Clinical_Heart_S)[4]<-"Axis"
colnames(Clinical_Heart_S)[5]<-"Score"
Clinical_Heart_S0<-Clinical_Heart_S[complete.cases(Clinical_Heart_S), ]
```

```{r plot ,echo=FALSE}
plots <- list()

plots[[1]] <- ggboxplot(Clinical_Heart_S0[Clinical_Heart_S0$Axis=="X1",], x = "Value", y ="Score",col="Value", palette = "jco",add = "jitter")+ylab("Axis 1") + facet_grid(~Trait) +  stat_compare_means() + theme(legend.position="none")

plots[[2]] <- ggboxplot(Clinical_Heart_S0[Clinical_Heart_S0$Axis=="X2",], x = "Value", y ="Score",col="Value", palette = "jco",add = "jitter")+ylab("Axis 2")  + facet_grid(~Trait) +  stat_compare_means() + theme(legend.position="none")

plots[[3]] <- ggboxplot(Clinical_Heart_S0[Clinical_Heart_S0$Axis=="X3",], x = "Value", y ="Score",col="Value", palette = "jco",add = "jitter")+ylab("Axis 3")  + facet_grid(~Trait) +  stat_compare_means() + theme(legend.position="none")

multiplot(plotlist = plots, cols = 1)

```
