---
title: "Comparison multiple approach"
author: "Cynthia Sandor"
date: 'Last update: `r date()`'
output:
  html_document:
    fig_height: 5
    fig_width: 5
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 5
  pdf_document:
    toc: yes
---


```{r setup, include=FALSE}
setwd("/Users/dpag0499/Dropbox (UK Dementia Research Institute)/Sandor Lab/Backup/PROJECTS/PPMI/src/new_Figures/Fig2")
library(ggplot2)
library(gplots)
library(reshape)
library(plyr)

```

```{r get comparison four methods, include=FALSE}
load("data_analysis.Rdata")
```

```{r make plot, include=FALSE}


p <- ggplot(df_analysis_weight, aes(Discovery_Norm, PPMI_Norm))+
geom_point(aes(colour = factor(Axis3)),size=4)+
facet_grid(factor(Method,levels=c('Phenix','PCA','ICA','MDS')) ~Axis3)+
geom_text(aes(label=Cat),size=4,hjust=0, vjust=0) + 
  xlim(-1, 1)+ ylim(-1,1)+ 
  geom_abline(intercept =0, slope = 1)+
  theme(axis.text=element_text(size=10),axis.title=element_text(size=18))+ 
  theme(legend.position="none")+
  theme(strip.text.x = element_text(size = 20))+
  theme(strip.text.y = element_text(size = 20))

p<-p+  geom_label(data=regression_data_mod, inherit.aes=FALSE, aes(x = -0.5, y = 0.8,label=paste("R^2=",R2," p=",round(Pval,3))))+ labs(x = "Discovery", y="PPMI")

p
```

